name: barikoi_api
version: 0.0.1
description: My API Client
homepage: homepage

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  dio: ^4.0.4
  built_value: ^8.1.4
  built_collection: ^5.1.1
  analyzer: ^3.2.0

dev_dependencies:
  built_value_generator: ^8.1.4
  build_runner: any
  test: ^1.20.1

